# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mood_mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mood_mobile
  pod 'GoogleSignIn', '~> 4.4.0'

  target 'mood_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mood_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
