# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'increment_build_number'
  lane :inc_build do
      increment_build_number(xcodeproj: './ios/mood_mobile.xcodeproj')
  end
  
  desc 'Push a new beta build to TestFlight'
  lane :beta do
    match(
      type: 'appstore',
      git_url: 'https://github.com/SamRond/mood_mobile_certs'
    ) # more info: https://codesigning.guide
    increment_build_number(xcodeproj: './ios/mood_mobile.xcodeproj')
    gym(scheme: 'mood_mobile', workspace: './ios/mood_mobile.xcworkspace')
    upload_to_testflight
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    match(
      type: 'appstore',
      git_url: 'https://github.com/SamRond/mood_mobile_certs'
    )
    increment_build_number(xcodeproj: './ios/mood_mobile.xcodeproj')
    gym(scheme: 'mood_mobile', workspace: './ios/mood_mobile.xcworkspace')
    upload_to_app_store(screenshots_path: './fastlane/screenshots')
  end

  desc 'Upload new screenshots to App Store'
  lane :screenshots do
    deliver(
      submit_for_review: false,
      skip_binary_upload: true
    )
  end
end

platform :android do
  desc 'Build a release APK for beta usage'
  lane :beta do
    gradle(
      project_dir: './android',
      task: 'clean assembleRelease')
  end

  desc 'Deploy a new version to the Play Store'
  lane :release do
    # todo: capture_screenshots
    gradle(
      project_dir: './android',
      task: 'clean assembleRelease')
    upload_to_play_store # requires `supply` setup https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply
  end
end
